[project]
name = "macrostrat-ml-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.36",
    "fastapi[standard]>=0.115.12",
    "python-dotenv>=1.1.0",
    "setfit>=1.1.2",
    "uvicorn>=0.34.3",
]
